config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  broadcasts_refreshes
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    @turbo_action = params['turbo_action'] || params['post']['turbo_action']

    @post.update(post_params) if params['post']


    # For non-morph the Modal.show method will be called in the connect method in modal_controller.ts
    # This will add another backdrop layer, so we need to manually remove that.
    # For morhp methods, it will only be called the first time we insert the HTML.
    respond_to do |format|
      format.turbo_stream do
        case @turbo_action
        in 'replace'
          # replace replaces the whole #element modal, so we wrap edit in a <div id="modals"> to ensure we keep the element
          render turbo_stream: [
            turbo_stream.action(:remove_backdrop, 'body'),
            turbo_stream.replace("modals",
                                 "<div id=\"modals\">#{render_to_string template: 'posts/edit'}</div>")
          ]
        in 'replace_morph'
          render turbo_stream: [
            turbo_stream.replace("modals",
                                 "<div id=\"modals\">#{render_to_string template: 'posts/edit'}</div>",
                                 method: :morph)

          # Instead of calling open_modal we just set the `class: show` and `display: block` directly in the modal
          # template.
          # turbo_stream.action(:open_modal, "edit-modal")
          ]
        in 'update'
          render turbo_stream: [
            # Removing the backdrop can also be done in the modal connect method
            turbo_stream.action(:remove_backdrop, 'body'),
            turbo_stream.update("modals", template: "posts/edit")
          ]
        in 'update_morph'
          render turbo_stream: [
            turbo_stream.update("modals", template: "posts/edit", method: :morph),
            # turbo_stream.action(:open_modal, "edit-modal")
          ]
        in 'update_inner_modal'
          render turbo_stream: turbo_stream.update("edit-modal", partial: "posts/edit_inner_modal")
        in 'update_inner_modal_morph'
          render turbo_stream: turbo_stream.update("edit-modal", partial: "posts/edit_inner_modal", method: :morph)
        end
      end
      format.html { render :edit }
    end
  end

  # POST /posts or /posts.json
  def create
    # assign the User record we just made for demo purposes
    @post = Post.new(post_params.merge(user: User.first))

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_path, notice: "Post was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params.expect(:id))
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.expect(post: [:title, :content, :available_on, :user_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_path, notice: "User was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.expect(user: [ :name, :email ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Turbomorphtest" %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= turbo_refreshes_with method: :morph, scroll: :preserve  %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" data-turbo-track="reload">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css" data-turbo-track="reload">
    
    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous" data-turbo-track="reload"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous" data-turbo-track="reload"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr" data-turbo-track="reload"></script>

    <%#= vite_client_tag %>
    <%= vite_typescript_tag 'application' %>
  </head>

  <body>
    <main class="container">
      <%= yield %>
    </main>
    <div id="modals"></div>
  </body>
</html>

app/views/posts/_edit_inner_modal.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title">Editing post</h5>
      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <div class="modal-body">
      <%= render "form", post: @post %>
      <br>
    </div>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post, class: "row g-3", data: { controller: "turbo-form" }, id: 'edit_form') do |form| %>
  <% if post.errors.any? %>
    <div class="col-12">
      <div class="alert alert-danger">
        <h4><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h4>
        <ul class="mb-0">
          <% post.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <!-- Setting `autofocus` does not work, see readme for more info. -->
  <div class="col-md-6">
    <%= form.label :title, class: "form-label" %>
    <!-- Changing this field will fetch an update from the server -->
    <%= form.text_field :title, class: "form-control", data: { action: 'change->turbo-form#update' } %>
  </div>

  <div class="col-md-6">
    <%= form.label :available_on, class: "form-label" %>
    <!--
    Need to use data-turbo-permanent on flatpickr fields
    -->
    <div data-turbo-permanent>
      <%= form.text_field :available_on, class: "form-control", data: { controller: "flatpickr" } %>
    </div>
  </div>

  <div class="col-12">
    <%= form.label :content, class: "form-label" %>
    <%= form.textarea :content, class: "form-control", rows: 4 %>
  </div>

  <div class="col-md-6">
    <%= form.label :turbo_action, class: "form-label" %>
    <%= form.select :turbo_action,
                    options_for_select([
                                         ['Replace', 'replace'],
                                         ['Replace Morph', 'replace_morph'],
                                         ['Update', 'update'],
                                         ['Update Morph', 'update_morph'],
                                         ['Update Inner Modal', 'update_inner_modal'],
                                         ['Update Inner Modal Morph', 'update_inner_modal_morph']
                                       ], @turbo_action),
                    { prompt: 'Select turbo action' },
                    { class: "form-select" } %>
  </div>

  <%= form.hidden_field :id, data: { autoreload_target: "postId" } %>

  <div class="col-12">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= post.content %>
  </p>

  <p>
    <strong>Available on:</strong>
    <%= post.available_on %>
  </p>

  <p>
    <strong>User:</strong>
    <%= post.user_id %>
  </p>

</div>

app/views/posts/edit.html.erb
<% content_for :title, "Editing post" %>

<div class="modal show" tabindex="-1" data-controller="modal" id="edit-modal" style="display:block">
  <%= render partial: "edit_inner_modal" %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Posts" %>

<% if notice.present? %>
  <p id="notice"><%= notice %></p>
<% end %>
<%= render "posts/form", post: Post.new %>


<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<% content_for :title, "New post" %>

<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= turbo_stream_from @post %>

<%= render @post %>

<%#= form_with(model: @post) do |form| %>
<!--  <div data-turbo-permanent>-->
<%#= form.label :available_on, style: "display: block" %>
<%#= form.date_field :available_on, data: { controller: "flatpickr" } %>
<!--  </div>-->
<%# end %>

<!--<div data-turbo-permanent>-->
<!--  <label for="standalone_date" style="display: block">Data permanent</label>-->
<!--  <input type="date" id="standalone_date" data-controller="flatpickr">-->
<!--</div>-->

<!--<div data-turbo-permanent>-->
<!--  <label for="standalone_date2" style="display: block">No data-permanent</label>-->
<!--  <input type="date" id="standalone_date2" data-controller="flatpickr">-->
<!--</div>-->

<!--<div data-turbo-permanent id="flatpickr-container"></div>-->

<div data-turbo-prefetch="false">
  Edit:
  <ul>
    <li>
      <%= link_to "Edit this post", edit_post_path(@post) %>
    </li>
    <li>
      <%= link_to "Edit with turbo (replace)",
                  edit_post_path(@post, format: :turbo_stream, turbo_action: "replace") %>
    </li>
    <li>
      <%= link_to "Edit with turbo (replace_morph)",
                  edit_post_path(@post, format: :turbo_stream, turbo_action: "replace_morph") %>
    </li>
    <li>
      <%= link_to "Edit with turbo (update)",
                  edit_post_path(@post, format: :turbo_stream, turbo_action: "update") %>
    </li>
    <li>
      <%= link_to "Edit with turbo (update_morph)",
                  edit_post_path(@post, format: :turbo_stream, turbo_action: "update_morph") %>
    </li>
    <li>
      <%= link_to "Edit with turbo (update)  - inner modal",
                  edit_post_path(@post, format: :turbo_stream, turbo_action: "update_inner_modal") %>
    </li>
    <li>
      <%= link_to "Edit with turbo (update_morph) - inner modal",
                  edit_post_path(@post, format: :turbo_stream, turbo_action: "update_inner_modal_morph") %>
    </li>
  </ul>
  Other:
  <%= link_to "Back to posts", posts_path %>
  <%= button_to "Destroy this post", @post, method: :delete %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

</div>

app/views/users/edit.html.erb
<% content_for :title, "Editing user" %>

<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Users" %>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<% content_for :title, "New user" %>

<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>